import { DomainError } from "../errors/domain.error.js";

/**
 * Thrown when an {@link AccountId} is constructed from an empty or blank string.
 *
 * @public
 */
export class InvalidAccountIdError extends DomainError {
  public override readonly code = "INVALID_ACCOUNT_ID" as const;

  constructor() {
    super("AccountId cannot be empty.");
  }
}

/**
 * Value object that wraps a non-empty string identifier for an account.
 *
 * All IDs in this library are plain strings (e.g. UUIDs generated by
 * `crypto.randomUUID()`).  Using a value object instead of a raw `string`
 * makes intent explicit and prevents accidental misuse of arbitrary strings
 * as identifiers.
 *
 * @example
 * ```ts
 * const id = new AccountId(crypto.randomUUID());
 * id.value; // "550e8400-e29b-41d4-a716-446655440000"
 * id.equals(other); // structural equality
 * ```
 *
 * @public
 */
export class AccountId {
  /** The underlying string identifier. */
  public readonly value: string;

  /**
   * @param raw - A non-empty string identifier (e.g. a UUID v4).
   * @throws {InvalidAccountIdError} When `raw` is empty or contains only whitespace.
   */
  constructor(raw: string) {
    const trimmed = raw.trim();
    if (!trimmed) {
      throw new InvalidAccountIdError();
    }
    this.value = trimmed;
  }

  /**
   * Structural equality check.
   *
   * @param other - The other {@link AccountId} to compare against.
   * @returns `true` when both IDs hold the same string value.
   */
  public equals(other: AccountId): boolean {
    return this.value === other.value;
  }
}
