import { DomainError } from "../errors/domain.error.js";

/**
 * Thrown when a {@link CredentialId} is constructed from an empty or blank string.
 *
 * @public
 */
export class InvalidCredentialIdError extends DomainError {
  public override readonly code = "INVALID_CREDENTIAL_ID" as const;

  constructor() {
    super("CredentialId cannot be empty.");
  }
}

/**
 * Value object that wraps a non-empty string identifier for a credential.
 *
 * All IDs in this library are plain strings (e.g. UUIDs generated by
 * `crypto.randomUUID()`).  Using a value object instead of a raw `string`
 * makes intent explicit and prevents accidental misuse of arbitrary strings
 * as identifiers.
 *
 * @example
 * ```ts
 * const id = new CredentialId(crypto.randomUUID());
 * id.value; // "550e8400-e29b-41d4-a716-446655440000"
 * id.equals(other); // structural equality
 * ```
 *
 * @public
 */
export class CredentialId {
  /** The underlying string identifier. */
  public readonly value: string;

  /**
   * @param raw - A non-empty string identifier (e.g. a UUID v4).
   * @throws {InvalidCredentialIdError} When `raw` is empty or contains only whitespace.
   */
  constructor(raw: string) {
    if (!raw || raw.trim() === "") {
      throw new InvalidCredentialIdError();
    }
    this.value = raw;
  }

  /**
   * Structural equality check.
   *
   * @param other - The other {@link CredentialId} to compare against.
   * @returns `true` when both IDs hold the same string value.
   */
  public equals(other: CredentialId): boolean {
    return this.value === other.value;
  }
}
