export const WHOAMI_USER_REPOSITORY = "WHOAMI_USER_REPOSITORY";
export const WHOAMI_GOOGLE_USER_REPOSITORY = "WHOAMI_GOOGLE_USER_REPOSITORY";
export const WHOAMI_REFRESH_TOKEN_REPOSITORY =
  "WHOAMI_REFRESH_TOKEN_REPOSITORY";
export const WHOAMI_PASSWORD_HASHER = "WHOAMI_PASSWORD_HASHER";
export const WHOAMI_TOKEN_HASHER = "WHOAMI_TOKEN_HASHER";
export const WHOAMI_TOKEN_SIGNER = "WHOAMI_TOKEN_SIGNER";
export const WHOAMI_GOOGLE_ID_TOKEN_VERIFIER =
  "WHOAMI_GOOGLE_ID_TOKEN_VERIFIER";
export const WHOAMI_LOGGER = "WHOAMI_LOGGER";
export const WHOAMI_TOKEN_EXTRACTOR = "WHOAMI_TOKEN_EXTRACTOR";
export const WHOAMI_CONFIGURATION = "WHOAMI_CONFIGURATION";
