name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Version & Publish
    runs-on: ubuntu-latest

    # We need permissions to push tags and create Pull Requests
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - name: 🛎️ Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10

      - name: ⚙️ Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: 📥 Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: 🚀 Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This command automatically bumps package.json and updates CHANGELOG.md
          version: pnpm version
          # This command builds the project and publishes it
          publish: pnpm release
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
